version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - API_KEY=${API_KEY}
      - RPC_URL=${RPC_URL}
      - TX_STATUS_URL=${TX_STATUS_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NAME_SPACE=${NAME_SPACE}
    volumes:
      - .:/app  # .env dosyasını konteynere bağlar
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mamathon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=brokolif
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge